spring:
  security:
    oauth2:
      client:
        registration:
#          google:
#            client-id: 발급받은 키
#            client-secret: 발급받은 키
#            scope: profile, email
#            
          kakao:
            authorization-grant-type: authorization_code
            client-id: 0de5e34431d0d6ef10d353e97efbfe96
            client-secret: XvOVbHHMKS4ZG58yADw67iQN5Gaa05b4
            client-authentication-method: POST
            redirect-uri: http://localhost/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
            
#          naver:
#            client-id: 발급받은 키
#            client-secret: 발급받은 키
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope: name, email
#            client-name: Naver

        provider:  
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id  
            
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response